import './globals.css'
import Head from 'next/head'

export const metadata = {
  title: 'Ballı UI Dev Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    
    <html lang="en" >
  
      <body className='home'>{children}</body>
    </html>
  )
}
